# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test for linux

on:
  push:
    branches:
      - '3.1.*'
  pull_request:
    branches:
      - '3.1.*'

jobs:
  unit_test_for_jdk17:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'
        distribution: 'adopt-hotspot'
        cache: 'maven'
    - name: Test with Maven
      run: mvn clean install -DskipTests -Dmaven.javadoc.skip=true -B -U
        && sh ./check_format.sh
        && mvn test  -DargLine="-Djdk.util.zip.disableZip64ExtraFieldValidation=true"
    - name: Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
